apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautilus-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rama3319/helm-to-argo.git
    targetRevision: HEAD
    path: nautilus-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
