app:
  app:
    name: nautilus-app
  image:
    repository: nginx
    tag: "1.27"
  replicaCount: 1
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: traefik
    host: nautilus-app.local
    path: /
    pathType: Prefix
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
